apiVersion: v1
kind: Service
metadata:
  name: concourse-web
  labels:
    app: concourse-web
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      $patch: delete
    - port: 80
      name: atc
      protocol: TCP
      targetPort: atc
    - port: 9391
      name: prometheus
      protocol: TCP
      targetPort: prometheus
