apiVersion: v1
kind: Service
metadata:
  name: concourse-postgresql
  labels:
    app: concourse-postgresql
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      name: postgresql
      targetPort: postgresql
  selector:
    app: concourse-postgresql
